### PR TITLE
Replace lucadegasperi/oauth2-server-laravel with laravel/passport

### PR DESCRIPTION
**Pull request by tomdiggle**
This PR replaces the deprecated lucadegasperi/oauth2-server-laravel with laravel/passport (Issue: #216). There doesn’t seem to be an easy way to migrate data so, the database migrations make a hard switch (not ideal) by dropping the necessary tables and recreating them. Tables that are not reused are dropped completely.

I've not generated the Passport Vue components to view clients, authorized clients and personal access tokens. They can be easily added if required.

I've kept the keys out of source control so, remember to run `php artisan passport:install` to create the encryption keys needed to generate secure access tokens. In addition, the command will create "personal access" and "password grant" clients which will be used to generate access tokens.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@tomdiggle Thank you so much for this. Looking forward to checking it out right now! Finally!

**Comment by mattstauffer** [comment]
Tested locally and everything seems to work fine.

Just need to coordinate a time with @rdohms to figure out the best time to push this (his app Pronto! is the primary consumer of our OAuth tokens)

**Comment by m1guelpf** [comment]
@mattstauffer Once this is pulled in, I'll start migrating the app to Laravel 5.5!

**Comment by tomdiggle** [comment]
Thanks for reviewing the PR. This was my first time working with Laravel Passport so I'm glad it all works. I'll be happy to make the changes you requested but it might not be until this Sunday before I get time.

**Comment by tomdiggle** [comment]
I've managed get a little bit of time to refactor the Api tests. Just pushed changes that bring back the `ApiTestCase`.

**Comment by mattstauffer** [comment]
image

Got a thumbs up from Raf to just go ahead. Gonna do that. Reviewing, merging, deploying.

**Pull request merged**
