### PR TITLE
Laravel 5.2 Shift

### PR DESCRIPTION
**Pull request by laravel-shift**
This pull request includes the changes for upgrading to Laravel 5.2.

**Before merging**, you should:

- Checkout the `laravel-5.2-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application

Commit any additional changes to the `laravel-5.2-shift` branch. If there were changes you feel could have been automated, please leave a comment on this pull request to help improve *Laravel Shift*.

### CODE REVIEW

**Comment by laravel-shift** [comment]
Laravel 5.2 modified the default Middleware. Since your middleware differs from the Laravel 5.1 default, you will need to compare the following middleware against the 5.2 versions and merge any changes.

- app/Http/Middleware/Authenticate.php
- app/Http/Middleware/EncryptCookies.php
- app/Http/Middleware/RedirectIfAuthenticated.php

**Comment by laravel-shift** [comment]
Laravel 5.2 adds *Middleware Groups* for convenience. Since this may require changes to your routes and controllers, I did not upgrade `app/Http/Kernel.php`. You should review [Middleware Groups](http://laravel.com/docs/5.2/middleware#middleware-groups) in more detail. When ready, merge your `app/Http/Kernel.php` with the [5.2 version](https://github.com/laravel/laravel/blob/becd774e049fb451aca0c7dc4f6d86d7bc12256c/app/Http/Kernel.php) and update your routes/controllers manually.

**Comment by laravel-shift** [comment]
The Authentication configuration changed significantly in Laravel 5.2. Since your `config/auth.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel/laravel/blob/becd774e049fb451aca0c7dc4f6d86d7bc12256c/config/auth.php) and merge any changes.

**Comment by laravel-shift** [comment]
Laravel 5.2 condenses the default User model dramatically. Since your `app/models/User.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel/laravel/blob/becd774e049fb451aca0c7dc4f6d86d7bc12256c/app/User.php) and merge any changes.

**Comment by laravel-shift** [comment]
`pluck`, `keys`, `zip`, `collapse`, `flatten`, `flip` now return a collection in Laravel 5.2. You should review your usage of these methods.

I found potential uses of these methods in:

- app/Commands/DestroySubmission.php

**Comment by laravel-shift** [comment]
`slice`, `chunk`, and `reverse` methods now preserve keys on the collection in Laravel 5.2. You should review your usage of these methods.

I found potential uses of these methods in:

- app/Http/Controllers/Api/ConferencesController.php

**Comment by laravel-shift** [comment]
Laravel 5.2 updated the `database` session driver. If you are using the `database` driver, you need to add the `user_id` (nullable integer), `ip_address` (nullable string), and `user_agent` (text) columns to your session database table.

**Comment by laravel-shift** [comment]
Laravel 5.2 now prefers using `get()` on the request object instead of the `Input` facade. Since I found potential references to the `Input` facade, I did not remove the alias in `app/config.php`.

If you would like to upgrade to using the request object, review the potential references of the `Input` facade in:

- app/Http/Controllers/OAuthController.php
- app/Http/Controllers/ConferencesController.php
- app/Http/Controllers/BiosController.php
- app/Http/Controllers/TalksController.php
- app/Http/Controllers/Api/ConferencesController.php
- app/macros.php

**Comment by laravel-shift** [comment]
Laravel 5.2 removed the `pretend` mail configuration option. If you were using `pretend`, use the `log` driver instead.

**Comment by mattstauffer** [comment]
- [ ] "admin-auth" Route filter in RouteServiceProvider needs to be middleware instead

**Comment by mattstauffer** [comment]
- [ ] handle usages of "User" instead of "App\User"
- [ ] Make sure re-publishing OAuth migrations didn't break anything

**Comment by mattstauffer** [comment]
@rdohms This PR is upgrading us to Laravel 5.2 but also included a lot of dependency upgrades, including OAuth server. I want to push this out at a time when you're around and we can debug its connection to Pronto! together. Do you have any time in the next week or so for that?

**Comment by rdohms** [comment]
I'm currently in funemployment... so yes, i'm wide open to help you out next week.
I will be on the road after the 11th.

**Comment by rdohms** [comment]
Get me a branch to test against locally and i should be able to give you a 👍  or 👎

**Comment by mattstauffer** [comment]
@rdohms great, thanks! This PR'ed branch should work:

https://github.com/tightenco/symposium/tree/laravel-5.2-shift

**Comment by rdohms** [comment]
Roger, will try it on monday probably.

**Comment by rdohms** [comment]
So Chrome is telling me "Authorization page could not be loaded." and i really can't open the oauth/authorize page without getting a 500 error, problem is I get nothing in the logs to hint at the issue. Any ideas?

**Comment by mattstauffer** [comment]
Hm I'll take a look!

Sent from Outlook for iOS




On Sat, Jun 4, 2016 at 5:25 AM -0700, "Rafael Dohms" <notifications@github.com> wrote:












So Chrome is telling me "Authorization page could not be loaded." and i really can't open the oauth/authorize page without getting a 500 error, problem is I get nothing in the logs to hint at the issue. Any ideas?

**Comment by mattstauffer** [comment]
@rdohms OK, just fixed a bug there--try it again when you get a chance!

**Comment by mattstauffer** [comment]
@rdohms Also, make sure your local `.env` file has `APP_DEBUG` set to true so you can see the errors echoed directly.

**Comment by rdohms** [comment]
Let me check it, but i do have APP_DEBUG on and still getting blank 500 page BTW.

**Comment by rdohms** [comment]
@mattstauffer all clear on my end, thanks for the heads up.

**Pull request merged**
