### PR TITLE
Feature - Send Open CFP Notification (#239, with matt's modifications)

### PR DESCRIPTION
**Pull request by mattstauffer**

### CODE REVIEW

**Comment by christophrumpel** [comment]
Hey, just looked through your commits. Looks good to me! So with Slack, you provide just the link again and then the admin checks the conf on the site and can approve it right? Maybe this is even better than approving right through the Slack message. This way an admin actually has to check the conference :-) Looking forward to trying these changes out 👍

**Comment by mattstauffer** [comment]
@christophrumpel yep! :)

**Comment by mattstauffer** [comment]
@christophrumpel We've got this up and running on staging.symposiumapp.com. Please feel free to test it out!

**Comment by christophrumpel** [comment]
Niceee 👍

**Comment by mattstauffer** [comment]
image

Just got my first one from the staging site. 11pm is a bit weird, so I'm guessing we have a server time zone issue.

**Comment by christophrumpel** [comment]
Hmm the cronjob is running every minute right? Do you see the time difference between the time the conference was imported and the notification?

**Comment by mattstauffer** [comment]
I guess it *could've*, but here's the record:

image

Feels super likely that 9am server time is 11pm my time... somehow. So I just need to dive in at some point and figure out the most appropriate space to set that sort of config.

image

The app is configured for Detroit, which is my time zone, so I'll have to do a deeper dive to try to figure out what's going on there.

Actually.. wait.. how did it even run?

image

It's set to only notify on prod?

I'm so confused. I'll have to take a closer look later.

**Comment by christophrumpel** [comment]
Hey Matt, if I remember correctly it works like that:

- when a new conference is imported, it checks if it already accepts CFPs, if yes we automatically send out the notification
- the cronjob is only for cases where a conference was added where the CFP was not open yet

This would explain why you got the email almost the same time the conference was added. Right?

**Comment by mattstauffer** [comment]
@christophrumpel oh my goodness I misread the created_at date. You're 100% right and i"m an idiot.

Thank you!

**Comment by christophrumpel** [comment]
np at all. It is difficult to remember those things. I wrote it and even I wasn't sure about it :-)

**Pull request merged**
