### PR TITLE
Allow for both filtering and sorting on conferences

### LINKED ISSUE #60: Hide or minimize conferences that are over
If both the conference CFP *and* the conference are over, they should be less prominent or invisible in the main conferences view

### PR DESCRIPTION
**Pull request by mattstauffer**
image

Note at least two places in which I suggest I hate myself for writing the code I did. Would love input.

Fixes #60

### CODE REVIEW

**Comment by adamwathan** [comment]
More friendly product design discussion:

When do you see a speaker taking advantage of the sorting and filtering options?

Not trying to be slow, trying to validate that we have a reason to include this feature at all. If we can do less, there's less things competing for attention on the screen and less code to test and maintain and that's always good! :)

As a speaker myself, I can't think of a compelling reason to sort conferences alphabetically by title. Even being in a position where I'm trying to invent a reason for it is a bad place to be I think when it comes to making a product decision, so I really want to address the initial motivation for it and what the problem really is.

Sorting by "closing soonest" totally makes sense to me, as a solution to this very real problem I've experienced:

>_When I want to give a talk somewhere, I need to know what CFPs are closing soon to make sure I don't miss the deadline._

...and even that could be solved in a ton of ways that aren't a table, but putting a list of conferences right in my face when I log in as well and putting the urgent ones first is definitely going to help.

To obey Wathan's Law, I'll get this in here now, from [this amazing podcast episode](http://jobstobedone.org/radio/ryan-singer-jtbd-radio/):

> **Ryan:** There’s this thing that I see all the time, and this is kind of what
> I wanted to say in the beginning, with the way that people
> usually approach business software, especially if they’re
> getting hired to do it on a client service basis. They’re so
> afraid of doing the wrong thing, or they don’t know clearly what
> is important, so they kind of cast a net where they don’t know
> where the value is, so they build 100 features and then throw
> those 100 features at the customer and hope that they stick onto
> one of them.
>
> **Bob:** Yep.
>
> **Ryan:** You know? And the question is, how do you figure out which of those
> features is actually the important thing? And that’s where the
> Jobs to be Done tools come in. One thing is that if we just talk
> to the customer about what software they want, they want
> everything because they don’t ever want to be lacking something.
>
> **Bob:** Right.
>
> **Ryan:** And they don’t really experience the development cost of having a lot
> of features; to them software doesn’t have a mass or a dimension
> really. The interface does, but people have this impression that
> software could just have . . . there’s no end to the number of
> things it could do because it’s kind of not so tangible, so it’s
> hard to see. So if you ask customers, do you want this feature?
> They’ll say yes. You ask, do you want this feature, too? And
> they’ll say, of course. How about this one? Yes, sounds great.
> Right?
>
> **Chris:** That’s right. They never say no.
>
> **Ryan:** Exactly, but then if you build all of that stuff, you’re over your
> deadline because you built all the stuff you didn’t need to
> build, they’re not even using it. And then on top of the fact
> these features that they don’t use they compete for space and
> for attention on the surfaces of the interface.
>
> **Bob:** Right. That’s right.
>
> **Ryan:** So you’re basically compromising the utility of the product in order
> to hedge against the risks that you didn’t know what to build.
> It really hits the fan in the user experience in the end,
> because the interface is so cluttered with stuff because you
> didn’t know what to focus on.
> So the Jobs to be Done thing is like, instead of asking people what
> they want, because they’re always going to tell you more things;
> desire is endless.
>
> **Bob:** Right.
>
> **Ryan:** There’s no end; there’s simply no end; it’s bottomless. But if you
> ask them about past situations where they struggled to address a
> problem, then they’re going to tell you about what they tried.
> And when they tell you what they tried that’s where they put
> their energy in, because we all have a certain number of hours
> in the day, and if we tried and tried and tried to get Microsoft
> Project to work, or if we . . . And then we talk about how we
> succeeded and how we failed, this reveals our real values from
> the demand side.

**Comment by mattstauffer** [comment]
I know you're not trying to be slow. :) And thank you so much for fulfilling Wathan's Law. Not sure what I would do without it. :D

All of this came out of either personal use cases (I was working on conference submissions in Symposium and needed something) or Twitter requests from users.

# Thoughts: 
**When do you see a speaker taking advantage of the sorting and filtering options?**
- Filter future: Default filter. Shows all conferences in the future. This is basically where you start from. It shows conferences that haven't happened, regardless of the CFP status, so that you can both be seeing open CFPs but also conferences you're marked as submitted/accepted to. It's the all-at-once glance.
- Filter CFP Is Open: Places where you can submit *today* if you want. If you come to the app figuring out "where can I submit?", you go here.
- Filter Unclosed CFP: CFPs that haven't closed yet, regardless of whether they've opened or not. This is where you go when you want to plan out what conferences you might apply to.
- Filter All time: All conferences. You go here to see past conferences as well as current. Might be better solved by "past conferences"--I was unsure about that one.
- Filter favorite: I added this after the screenshot. Lets you only see your favorited conferences. The purpose is so you can favorite any conference you have any sort of interest in, and then come back here to look at them, apply, update your application status, etc.

- Sort title: We can totally drop this one. It was just the first one I wrote.
- Sort Date: I would suggest this be the default, so we have a timeline of approaching conferences--both for understanding which CFPs to apply to, but also having a timeline of upcoming conferences, and which you've applied to/been accepted to/etc.
- CFP Closing next: like you said, shows the timeliness of which to apply to.

**Comment by mattstauffer** [comment]
Also: I'm 100% fine if we change the UI. I sort of expect we may. But I just want to get the functionality in there and toy around with it. Just my thoughts though, open to working on UI before we merge. :)

**Comment by adamwathan** [comment]
Cool, few more questions. Also want to emphasize that when I ask "when would you do x?" I 100% am not saying _"Why the hell would you ever need that feature"_, I am literally asking "when would you use it", to capture the context so we can make more informed decisions about the best solution. Read more like "what comes up or what situation are you in that prompts you to want to use this feature".

1. When would you want to look at a past conference?
2. What do you think makes more sense, being able to favorite conferences and then enable the filter that removes non-favorited conferences, or doing the opposite, and having something like a "Not interested" action that keeps track of ignored conferences, and doesn't show them unless you click a filter that says something like "Include ignored conferences"?

Specifically regarding 2, I ask because I have an idea for a less customizable default view that I think might work really well.

It would sort CFPs by closing date first, and by conference date second. So any conferences with an announced CFP will always be before conferences that haven't announced a CFP, and all conferences that haven't announced their CFP yet will be sorted by date.

As a speaker using Symposium to manage my proposals and plan my conference submissions, a conference isn't going to be any good to me until they have announced their CFP, and the vast majority will announce their CFP so far out from the actual conference that the number of times a conference will be on the list that is even on my radar but hasn't announced their CFP yet is essentially zero.

Rather than a favorite system that allows you to opt in to seeing only conferences you're interested in, a "dismiss" system would by default only show you conferences you're not _not_ interested in, allowing you to opt in to seeing all.

I wouldn't provide any sort options at all.

Filter-wise, all I would provide is a toggle for "Include dismissed conferences" (hopefully we can think of better copy for that), and a link to past conferences if you need to dive into the archives. I don't think diving into the archives is going to be a common enough use case to build into this interface, or maybe to even build as a priority at all.

I'm imagining something sort of like this:

image


Sidenote: I call that Affordance Driven Design. I have no idea how to make something look good, but thinking critically about what information is important and what's less important helps me design something that usually actually looks OK just by the nature of focusing on utility, haha...

**Comment by adamwathan** [comment]
^ @mattstauffer @besologic

**Comment by mattstauffer** [comment]
I totally get that you're not saying "why the hell did you think this." :) :heart:

RE: questions:
1. I'd want to look at a past conference if I wanted to get details about the conference in the past that I know I found here; to see what talk I submitted there. That's all I've got right now.
2. That's a great question. I've thought about it a few times and I can't decide.

I think your view looks super cool, but I miss the ability to see things based on a timeline of when the conferences are, since the CFPs are often totally different relationships to their conferences.

Also, I have a personal dislike of "dismissing" things because it's much easier for me to say "yes interested!" then "definitely not." I'm much more likely to like than dislike, favorite than dismiss. I recognize this may be something particular to people like me (whatever that is). We'll need some thoughts from the others.

However, what I'm interested in here is that it surfaces the idea that the *point* of looking at conferences in a Symposium space is primarily about their CFPs. So prioritizing that info is great.

Also, your draft is missing some options that are part of the complexity. What about CFPs that are over, for conferences that haven't happened yet? (valuable because I may have submitted to them) What about CFPs that haven't opened yet?

Another thing: this view is great if we don't think of it as the "all conferences" view, but rather the "cfps" view. We could theoretically show information not related to active/future CFPs (e.g. all conferences I've submitted to, etc.) elsewhere. The job of this pane may just be to help you find CFPs you will submit to later. But we just need to ensure that we're moving the other functionalities of this page elsewhere rather than just getting rid of them.

In general, though, I love the layout.

**Comment by adamwathan** [comment]
**CPFs vs. Conferences**

I think what you've brought up re: this page being about CFPs rather than conferences is a really interesting point. It would be good to capture the jobs we want Symposium to do that _are_ related to conferences, because you're right, a lot of them might be served better by a completely different part of the app. Some of them might be possible in a combined view too so I think we just need to capture them.

**Moar questions**

1. You mentioned looking at past conferences to see what talks you submitted, when and why do you want to which talks you submitted to previous conferences? What's the situation you are in that you think that information would help resolve?

2. RE: CFPs that are closed for conferences that haven't happened yet, what decisions is this information helping you make? When would you want to see it? I'm wondering if like mentioned previously, it makes sense to design a view like we have here that's focused on the job of keeping you on top of current CFPs, while "CFPs I've submitted to" might be part of something else, but it's important to figure out what the job is there.

3. RE: CFPs that are announced but not open yet, I think those could still be sorted above CFPs that haven't announced their dates, but keep the semi-transparent look since they are not actionable yet, or some better visual cue a better visual designer would come up with.

    Maybe something like this, but would love to figure out if this information could be conveyed even simpler:

image

**Favorite vs. Dismiss**

I think I agree that it's more natural to say "ooo yeah this looks like a good fit for me", the only reason I pitched the other one is because it removes the step of manually switching to the "show me my favorites" view, and you can't add _new_ favorites when you are already in that view (since you're only seeing things you've already favorited), so you have to keep toggling back and forth, and you can't show the favorited view by default because people would miss seeing new conferences they haven't favorited yet.

With a "dismiss" workflow, you could always default to the "not dismissed" view, which would show new conferences as they are added, but always hide things you've opted out of. I think it's a much simpler workflow with a lot of benefits, although again I do agree that favoriting feels more natural than dismissing in some ways.

That _might_ work in our favor though, because I think what you're saying and I agree, is that with dismiss vs. favorite, you would end up with different sets of CFPs. Like I'm not going to dismiss everything that I wouldn't have favorited, and I'm not going to favorite everything that I wouldn't have dismissed. My hunch is that favoriting would lead to a smaller list than "not dismissed", because people would only dismiss CFPs that they _really_ know they aren't interested in.

I dunno, I think I really like the simpler workflow that it creates, but I'm open to discussion. Maybe prototyping both would be the best way to figure out which solution feels like a better experience.

**Comment by mattstauffer** [comment]
I love pretty much everything you're saying and mocking up here. I'll look again when j get in to see if there are any outstanding questions but in general I think this is great stuff. 👍👍

Sent from Outlook




On Wed, May 13, 2015 at 4:10 AM -0700, "Adam Wathan" <notifications@github.com> wrote:












CPFs vs. Conferences



I think what you've brought up re: this page being about CFPs rather than conferences is a really interesting point. It would be good to capture the jobs we want Symposium to do that are related to conferences, because you're right, a lot of them might be served better by a completely different part of the app. Some of them might be possible in a combined view too so I think we just need to capture them.



Moar questions




You mentioned looking at past conferences to see what talks you submitted, when and why do you want to which talks you submitted to previous conferences? What's the situation you are in that you think that information would help resolve?


RE: CFPs that are closed for conferences that haven't happened yet, what decisions is this information helping you make? When would you want to see it? I'm wondering if like mentioned previously, it makes sense to design a view like we have here that's focused on the job of keeping you on top of current CFPs, while "CFPs I've submitted to" might be part of something else, but it's important to figure out what the job is there.



RE: CFPs that are announced but not open yet, I think those could still be sorted above CFPs that haven't announced their dates, but keep the semi-transparent look since they are not actionable yet, or some better visual cue a better visual designer would come up with.



Maybe something like this, but would love to figure out if this information could be conveyed even simpler:









Favorite vs. Dismiss



I think I agree that it's more natural to say "ooo yeah this looks like a good fit for me", the only reason I pitched the other one is because it removes the step of manually switching to the "show me my favorites" view, and you can't add new favorites when you are already in that view (since you're only seeing things you've already favorited), so you have to keep toggling back and forth, and you can't show the favorited view by default because people would miss seeing new conferences they haven't favorited yet.



With a "dismiss" workflow, you could always default to the "not dismissed" view, which would show new conferences as they are added, but always hide things you've opted out of. I think it's a much simpler workflow with a lot of benefits, although again I do agree that favoriting feels more natural than dismissing in some ways.



That might work in our favor though, because I think what you're saying and I agree, is that with dismiss vs. favorite, you would end up with different sets of CFPs. Like I'm not going to dismiss everything that I wouldn't have favorited, and I'm not going to favorite everything that I wouldn't have dismissed. My hunch is that favoriting would lead to a smaller list than "not dismissed", because people would only dismiss CFPs that they really know they aren't interested in.



I dunno, I think I really like the simpler workflow that it creates, but I'm open to discussion. Maybe prototyping both would be the best way to figure out which solution feels like a better experience.

**Comment by mattstauffer** [comment]
Moar answers:

1. The situation I'm in to look at past conferences is to, for example, look at what I talked about at Peers last year. Not only which talk did I give, but what was the particular wording I used? What bio did I submit there? Or, if I'm worried about the CFP not being open yet, take a look at when they opened the CFP last year to see what to expect.

2. CFPs that are closed for conferences that haven't happened yet, I care *if* I submitted. And I think we might want to consider a view that is "submitted talks" that handles this situation, like you're suggesting here.

3. I think that's fine; prioritize open CFPs, then yet-to-open CFPs, then TBA. I love it.

And I'm 100% down with "dismiss" instead of "favorite." I feel totally ready to start building on this, but I will yield if you want more process or if @besologic or others have feedback.

**Comment by adamwathan** [comment]
> The situation I'm in to look at past conferences is to, for example, look at what I talked about at Peers last year. Not only which talk did I give, but what was the particular wording I used? What bio did I submit there?

This is getting closer to the root motivation but not quite there. What I _am_ learning is that it sounds like maybe you're more interested in past _submissions_ than past CFPs :wink: 

What happens that makes you want to find out what you talked about at Peers last year? Why are you looking up what wording you used? Is it because you're working on a new talk and you want to follow the same formula that got your talk accepted at Peers? Or maybe you want to submit the same talk to another conference similar to Peers and you want to use the same wording? Or maybe it *didn't* get accepted to Peers and you're working on a new talk for next year's Peers and you want to see if you can figure out what you did wrong? All different motivations that are really gonna influence what the best solution is.

> Or, if I'm worried about the CFP not being open yet, take a look at when they opened the CFP last year to see what to expect.

This is super useful. I can already imagine another solution to this problem. In the list that shows the *next* FooConf with no CFP announced, we could literally stick in the card under "TBA", _"Last year was Aug 14"_. So no searching around at all necessary for the user and we solve the problem.

Not necessarily saying we should actually add this, but if that's the problem the speaker has, we can give them that information right away instead of making them dig through past conferences.

> 2. CFPs that are closed for conferences that haven't happened yet, I care *if* I submitted. And I think we might want to consider a view that is "submitted talks" that handles this situation, like you're suggesting here.

Yeah something to keep track of your submissions sounds right here. How to display that so it's as helpful as possible is something we'll have to figure out.

> 3. I think that's fine; prioritize open CFPs, then yet-to-open CFPs, then TBA. I love it.

Sweet!

> And I'm 100% down with "dismiss" instead of "favorite." I feel totally ready to start building on this, but I will yield if you want more process or if @besologic or others have feedback.

Awesome, yeah let's try it out!

**Comment by mattstauffer** [comment]
You all might hate me, but I'm still going to merge this PR. I have no qualms whatsoever with pulling the functionality out, but I think it helps Symposium meet needs well that won't otherwise be met until we complete at least #65. :)

**Pull request merged**
