### PR TITLE
updated encryption type

### PR DESCRIPTION
**Pull request by timacdonald**
This should fix the issue raised here on twitter: https://twitter.com/vmitchell85/status/822105032107626498

Regarding the out-dated encryption method. I quick search, but couldn't find any encryption in the project, but please confirm before merging!

Thanks,
Tim

### CODE REVIEW

**Comment by timacdonald** [comment]
this is actually still being discussed and may not be the appropriate solution

**Comment by timacdonald** [comment]
If this is suitable, and encryption isn't actually used in the app,  would you like me to update the readme:

---

# Requirements

- PHP >= 5.5.9
- ~~PHP mcrypt extension~~


---

and composer.json

```
        "lucadegasperi/oauth2-server-laravel": "5.1.4",
        "ext-mcrypt": "*", // ditch ??
        "recaptcha/php5": "^2.0",
```

**Comment by vmitchell85** [comment]
Looks like changing the encryption method does in fact allow everything to run fine. The McryptEncrypter class isn't used with the change in method so the deprecated function isn't ran.

**Comment by mattstauffer** [comment]
This was already handled as a part of the Laravel Shift upgrade--but thanks @vmitchell85! :)

**Pull request closed without merging**
