### PR TITLE
Laravel 7.x Shift

### PR DESCRIPTION
**Pull request by sariyana**
This pull request includes the changes for upgrading to Laravel 7.x. Feel free to commit any additional changes to the `shift-27713` branch.

**Before merging**, you need to:

- Checkout the `shift-27713` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 7
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

## Dependency updates

The following dependencies were replaced because they were not compatible with Laravel 7.
- `andreasindal/laravel-markdown` (replaced with `erusev/parsedown`)
- `maddhatter/laravel-fullcalendar` (replaced with `progcode/laravel-fullcalendar`)

### CODE REVIEW

**Comment by sariyana** [comment]
:warning: Laravel 7 adds CORS middleware and defaults the `middlewarePriority` internally so you only need to overwrite this property for customizations.

Shift attempted to automate these changes. But you should compare your `app/Http/Kernel.php`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/app/Http/Kernel.php) to finalize any changes.

**Comment by sariyana** [comment]
:information_source: Laravel 7 upgraded to Symfony 5 which passes instances of the `Throwable` interface instead of `Exception` instances to core components like the `Exceptions\Handler`.

Shift [automated this change](https://github.com/tightenco/symposium/pull/288/commits/6ea359e57ba9d556a5680bf38eec8ce7f7d90e89?w=1). However, if you receive a `Throwable` type mismatch error there may be additional references you need to convert.

**Comment by sariyana** [comment]
:information_source: Laravel 7 moved the Authentication components into a separate [`laravel/ui` package](https://github.com/laravel/ui), which includes the _make_ commands as well as the traits related to authentication.

Shift added this dependency for convenience. However, if you do not plan to use the Authentication components, you may remove this dependency as well as the `Auth` controllers from your application.

**Comment by sariyana** [comment]
:warning: The `MAIL_DRIVER` environment variable was renamed in Laravel 7 to `MAIL_MAILER` in order to support multiple mail configurations.

Shift attempted to automation this change, but you should review any additional environment configuration and update to the new variable name.

**Comment by sariyana** [comment]
:warning: Shift upgraded the following configuration files by defaulting them. This often makes the changes [easier to review](https://github.com/tightenco/symposium/pull/288/commits/8711faccd0763f63fecf05b81b633c2d9e5ddc25?w=1) and backfill any customizations which are not configurable through `ENV` variables.

If you have a lot of customizations, you may quickly undo this commit with `git revert` and make these [config file changes](https://github.com/laravel/laravel/compare/6.x...master#diff-ea70a5765dbab9fd8032c1d439521db8) manually.

- [ ] config/auth.php
- [ ] config/filesystems.php
- [ ] config/logging.php
- [ ] config/mail.php

**Comment by sariyana** [comment]
:information_source: Shift [updated your dependencies](https://github.com/tightenco/symposium/pull/288/commits/7a76575745e83a4c36aad8e7a9bf8fa7c3f40c8b?w=1) for Laravel 7. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 7.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by sariyana** [comment]
:information_source: Shift detected the use of Markdown mail templates. In Laravel 7, Markdown mail templates expect unindented HTML. If you previously published Laravel's default mail templates, you need to re-publish your mail templates or manually unindent them.

**Comment by sariyana** [comment]
:information_source: Laravel 7 removed some of the PHPUnit configuration in favor of the defaults. While this is not a required changed, it is a good opportunity to compare your `phpunit.xml`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/phpunit.xml) to modernize your configuration.

**Comment by sariyana** [comment]
:warning: Laravel 7 uses a new date format when serializing models. The previous format was `2019-12-02 20:01:00`. Now, dates are serialized using an ISO-8601 compatible date format of `2019-12-02T20:01:00.283041Z` in `UTC`.

**This does not affect how dates are stored**. Only how they are serialized when using the `toArray` or `toJson` Eloquent methods.

If you need to preserve the previous format, you may override the `serializeDate` method on your model. Review the [Date Serialization](https://laravel.com/docs/7.x/upgrade#date-serialization) section of the _Upgrade Guide_ for more details.

**Comment by sariyana** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 5. If you are directly interacting with Symfony components, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md) for additional changes.

**Comment by sariyana** [comment]
:tada: Congratulations, you're now running the latest version of Laravel.

The following _Shifts_ may be used ensure your application is fully upgraded and following practices recommended by Laravel and the community:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automates many of the suggestions found by the [_Laravel Linter_](https://laravelshift.com/opinionated-laravel-way-shift) and other _Shifts_.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and unit tests by analyzing your application.

You may run these _Shifts_ and stay upgraded forever as well by subscribing to a [Shifty Plans](https://laravelshift.com/shifty-plans).

**Comment by andrewmile** [comment]
The markdown dependency has been changed from `andreasindal/laravel-markdown` to `erusev/parsedown`.

The fullcalendar dependency has been changed from `maddhatter/laravel-fullcalendar` to `progcode/laravel-fullcalendar`.

There were a lot of calls to the `route` helper that were broken because the route parameters being passed did not match the named parameters defined in the route.  I reviewed all of the uses of the `route` helper and updated any that were broken.

All tests are now passing except for two registration related tests, which are skipped because of email registration being disabled.

**Pull request merged**
